import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';

const $=id=>document.getElementById(id);
const root=$('game-root'),joystickRoot=$('joystick'),joystickKnob=$('joystick-knob'),hint=$('hint'),harvestPanel=$('harvest'),harvestLabel=$('harvest-label'),harvestFill=$('harvest-fill'),woodCount=$('wood-count'),stoneCount=$('stone-count'),pickup=$('pickup');

const scene=new THREE.Scene();scene.background=new THREE.Color(0x9bc978);scene.fog=new THREE.Fog(0x9bc978,32,72);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.6));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;root.appendChild(renderer.domElement);
const camera=new THREE.PerspectiveCamera(40,innerWidth/innerHeight,.1,140);camera.position.set(12,14,15);
scene.add(new THREE.HemisphereLight(0xfff1c4,0x38522f,1.75));const sun=new THREE.DirectionalLight(0xffdfa0,3.1);sun.position.set(-12,20,10);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-30;sun.shadow.camera.right=30;sun.shadow.camera.top=30;sun.shadow.camera.bottom=-30;scene.add(sun);
const mat=(c,r=.88)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:0});
const M={grass:mat(0x6ea552),grass2:mat(0x5d9347),path:mat(0xb79058),wood:mat(0x70452b),darkWood:mat(0x44291d),roof:mat(0x914832),wall:mat(0xd0b37c),stone:mat(0x858982),stoneLight:mat(0xaaa99f),leaf:mat(0x4e8d3c),leaf2:mat(0x70ad4b),water:new THREE.MeshStandardMaterial({color:0x62b6c8,roughness:.22}),skin:mat(0xd39b6a),cloth:mat(0x315b3a),leather:mat(0x6b482f)};
function add(parent,g,m,p=[0,0,0],r=[0,0,0],s=[1,1,1],shadow=true){const o=new THREE.Mesh(g,m);o.position.set(...p);o.rotation.set(...r);o.scale.set(...s);o.castShadow=shadow;o.receiveShadow=true;parent.add(o);return o}
const world=new THREE.Group();scene.add(world);
add(world,new THREE.PlaneGeometry(100,100),M.grass,[0,0,0],[-Math.PI/2,0,0],[1,1,1],false);
function path(x,z,w,h,rot=0){add(world,new THREE.PlaneGeometry(w,h),M.path,[x,.018,z],[-Math.PI/2,0,rot],[1,1,1],false)}path(0,1,4.4,24);path(0,-2.6,21,3.6);path(0,4,15,3.1);
let seed=1337;const rnd=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);
function tuft(x,z,s=1){const g=new THREE.Group();g.position.set(x,0,z);for(let i=0;i<4;i++){const b=add(g,new THREE.ConeGeometry(.07,.55+rnd()*.3,4),i%2?M.grass2:M.leaf2,[(i-1.5)*.1,.3,(i%2)*.1]);b.rotation.z=(i-1.5)*.08}g.scale.setScalar(s);world.add(g)}
for(let i=0;i<70;i++){const x=(rnd()-.5)*40,z=(rnd()-.5)*40;if(Math.abs(x)<3.7&&Math.abs(z)<10)continue;tuft(x,z,.65+rnd()*.8)}
function flower(x,z,c){add(world,new THREE.CylinderGeometry(.025,.025,.42,5),mat(0x3f7437),[x,.21,z]);add(world,new THREE.SphereGeometry(.11,6,4),mat(c),[x,.48,z])}
for(let i=0;i<28;i++)flower(-5+rnd()*10,-4.8+rnd()*3.5,[0xe36c64,0xf1d36c,0xc9a4e4,0xf39b5b][i%4]);
function fence(x,z,len,rot=0){const g=new THREE.Group();g.position.set(x,0,z);g.rotation.y=rot;[-len/2,len/2].forEach(px=>add(g,new THREE.BoxGeometry(.18,1.25,.18),M.wood,[px,.62,0]));add(g,new THREE.BoxGeometry(len,.16,.16),M.wood,[0,.4,0]);add(g,new THREE.BoxGeometry(len,.16,.16),M.wood,[0,.85,0]);world.add(g)}fence(-6.6,-9.8,4.8);fence(6.6,-9.8,4.8);fence(-7.5,8,4.8);fence(7.5,8,4.8);

const cottage=new THREE.Group();cottage.position.set(0,0,-7.4);world.add(cottage);add(cottage,new THREE.BoxGeometry(5.6,2.6,4),M.wall,[0,1.3,0]);add(cottage,new THREE.ConeGeometry(4,2.35,4),M.roof,[0,3.2,0],[0,Math.PI/4,0]);add(cottage,new THREE.BoxGeometry(.95,1.9,.2),M.darkWood,[0,1,2.08]);[-1.6,1.6].forEach(x=>add(cottage,new THREE.BoxGeometry(.8,.8,.14),mat(0x9ed5d8),[x,1.5,2.08]));add(cottage,new THREE.BoxGeometry(.42,1.6,.42),M.stone,[1.8,3.45,-.25]);
const well=new THREE.Group();well.position.set(0,0,-1.8);world.add(well);add(well,new THREE.CylinderGeometry(1.05,1.2,.75,12),M.stone,[0,.38,0]);add(well,new THREE.CylinderGeometry(.76,.76,.06,20),M.water,[0,.78,0]);[-.95,.95].forEach(x=>add(well,new THREE.BoxGeometry(.18,2.2,.18),M.wood,[x,1.45,0]));add(well,new THREE.BoxGeometry(2.2,.18,.18),M.wood,[0,2.35,0]);
function tree(x,z,s=1){const g=new THREE.Group();g.position.set(x,0,z);g.scale.setScalar(s);add(g,new THREE.CylinderGeometry(.42,.64,3.7,7),M.wood,[0,1.85,0]);add(g,new THREE.IcosahedronGeometry(1.7,1),M.leaf,[-.7,4.05,.1]);add(g,new THREE.IcosahedronGeometry(1.75,1),M.leaf2,[.65,4.3,0]);add(g,new THREE.IcosahedronGeometry(1.9,1),M.leaf,[0,5,-.2]);world.add(g);return g}
function rocks(x,z){const g=new THREE.Group();g.position.set(x,0,z);world.add(g);[[-.5,.6,0,1.15,M.stone],[.55,.45,.25,.85,M.stoneLight],[.1,.3,-.6,.7,M.stone]].forEach(([rx,ry,rz,s,m])=>{const r=add(g,new THREE.DodecahedronGeometry(.8,0),m,[rx,ry,rz],[rnd(),rnd(),rnd()],[s,s*.8,s]);});return g}
const treeObj=tree(-6.6,2.7,1.05),rockObj=rocks(6.3,3);
// background dressing
[[-11,-4,.9],[-13,7,1.05],[12,-5,.8],[14,8,1.0]].forEach(([x,z,s])=>tree(x,z,s));[[-10,10],[10,11]].forEach(([x,z])=>rocks(x,z));

const player=new THREE.Group();world.add(player);player.position.set(0,0,5);const body=add(player,new THREE.CapsuleGeometry(.42,.9,4,8),M.cloth,[0,1.15,0]);add(player,new THREE.SphereGeometry(.38,8,6),M.skin,[0,2.05,0]);add(player,new THREE.ConeGeometry(.48,.45,6),mat(0x593625),[0,2.42,0]);add(player,new THREE.BoxGeometry(.68,.85,.26),M.leather,[0,1.38,-.46]);const legL=add(player,new THREE.BoxGeometry(.2,.78,.2),M.darkWood,[-.42,.58,0]);const legR=add(player,new THREE.BoxGeometry(.2,.78,.2),M.darkWood,[.42,.58,0]);const axe=new THREE.Group();axe.position.set(.52,1.1,.02);add(axe,new THREE.CylinderGeometry(.045,.045,.9,6),M.wood,[0,-.1,0],[0,0,.25]);add(axe,new THREE.BoxGeometry(.38,.18,.08),M.stone,[.12,.32,0],[0,0,.25]);player.add(axe);

const keys=new Set();addEventListener('keydown',e=>keys.add(e.key.toLowerCase()));addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
const stick={pointerId:null,x:0,y:0};function updateStick(e){const r=joystickRoot.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,max=r.width*.34;let dx=e.clientX-cx,dy=e.clientY-cy;const l=Math.hypot(dx,dy)||1;if(l>max){dx=dx/l*max;dy=dy/l*max}stick.x=dx/max;stick.y=dy/max;joystickKnob.style.transform=`translate(calc(-50% + ${dx}px),calc(-50% + ${dy}px))`}joystickRoot.addEventListener('pointerdown',e=>{stick.pointerId=e.pointerId;joystickRoot.setPointerCapture?.(e.pointerId);updateStick(e)});addEventListener('pointermove',e=>{if(e.pointerId===stick.pointerId)updateStick(e)});function release(e){if(e.pointerId!==stick.pointerId)return;stick.pointerId=null;stick.x=0;stick.y=0;joystickKnob.style.transform='translate(-50%,-50%)'}addEventListener('pointerup',release);addEventListener('pointercancel',release);

const colliders=[{x:0,z:-7.4,r:3.2},{x:0,z:-1.8,r:1.35}];const resources=[{name:'Tree',type:'wood',icon:'🪵',object:treeObj,x:-6.6,z:2.7,r:1.25,yield:3,respawn:0,active:true},{name:'Rock',type:'stone',icon:'🪨',object:rockObj,x:6.3,z:3,r:1.1,yield:2,respawn:0,active:true}];const inventory={wood:0,stone:0};let current=null,harvestTime=0,pickupTimer=0;
function updateHud(){woodCount.textContent=inventory.wood;stoneCount.textContent=inventory.stone}updateHud();
function showPickup(text){pickup.textContent=text;pickup.classList.remove('hidden');pickupTimer=1.4}
function tryMove(dx,dz){const nx=THREE.MathUtils.clamp(player.position.x+dx,-19,19),nz=THREE.MathUtils.clamp(player.position.z+dz,-19,19);for(const c of colliders)if(Math.hypot(nx-c.x,nz-c.z)<c.r+.48)return;player.position.set(nx,0,nz)}
function nearestResource(){let n=null,b=Infinity;for(const r of resources){if(!r.active)continue;const d=Math.hypot(player.position.x-r.x,player.position.z-r.z);if(d<b){b=d;n=r}}return n&&b<=n.r+1.15?{r:n,d:b}:null}
function updateHarvest(dt,moving){const hit=nearestResource();if(!hit){current=null;harvestTime=0;harvestPanel.classList.add('hidden');hint.classList.remove('hidden');axe.rotation.z=0;return}if(current!==hit.r){current=hit.r;harvestTime=0}if(moving){harvestTime=0;harvestPanel.classList.add('hidden');hint.textContent=`Stop near the ${current.name.toLowerCase()} to harvest.`;hint.classList.remove('hidden');return}hint.classList.add('hidden');harvestPanel.classList.remove('hidden');harvestTime+=dt;harvestLabel.textContent=`Harvesting ${current.name}`;harvestFill.style.width=`${Math.min(100,harvestTime/1.6*100)}%`;axe.rotation.z=Math.sin(performance.now()*.02)*.45;if(harvestTime>=1.6){inventory[current.type]+=current.yield;current.active=false;current.object.visible=false;current.respawn=7;showPickup(`+${current.yield} ${current.icon}`);updateHud();current=null;harvestTime=0;harvestPanel.classList.add('hidden')}}

const clock=new THREE.Clock(),cameraOffset=new THREE.Vector3(11.5,13.2,14.5),lookOffset=new THREE.Vector3(0,1.15,0),desiredCam=new THREE.Vector3(),desiredLook=new THREE.Vector3();let walkT=0;
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05);let mx=stick.x,my=stick.y;if(keys.has('a')||keys.has('arrowleft'))mx-=1;if(keys.has('d')||keys.has('arrowright'))mx+=1;if(keys.has('w')||keys.has('arrowup'))my-=1;if(keys.has('s')||keys.has('arrowdown'))my+=1;const len=Math.hypot(mx,my);if(len>1){mx/=len;my/=len}const moving=Math.hypot(mx,my)>.06;if(moving){tryMove(mx*4.35*dt,my*4.35*dt);const yaw=Math.atan2(mx,my);let d=yaw-player.rotation.y;d=Math.atan2(Math.sin(d),Math.cos(d));player.rotation.y+=d*Math.min(1,dt*12);walkT+=dt*10;body.position.y=1.15+Math.sin(walkT)*.045;legL.rotation.x=Math.sin(walkT)*.35;legR.rotation.x=-Math.sin(walkT)*.35}else{body.position.y=THREE.MathUtils.lerp(body.position.y,1.15,.18);legL.rotation.x*=.75;legR.rotation.x*=.75}for(const r of resources){if(r.active)continue;r.respawn-=dt;if(r.respawn<=0){r.active=true;r.object.visible=true;showPickup(`${r.name} respawned`)}}updateHarvest(dt,moving);if(pickupTimer>0){pickupTimer-=dt;if(pickupTimer<=0)pickup.classList.add('hidden')}desiredCam.copy(player.position).add(cameraOffset);camera.position.lerp(desiredCam,1-Math.pow(.008,dt));desiredLook.copy(player.position).add(lookOffset);camera.lookAt(desiredLook);renderer.render(scene,camera)}animate();
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
