export class IslandTerrain{
 constructor(THREE){this.T=THREE;this.radius=135;this.seaLevel=-2;this.seabedLevel=-5.2;}
 angularDistance(a,b){let d=a-b;while(d>Math.PI)d-=Math.PI*2;while(d<-Math.PI)d+=Math.PI*2;return d;}
 islandMetric(x,z){const sx=x+5,sz=z-3,a=Math.atan2(sz,sx),r=Math.hypot(sx*.9,sz*1.05);const baseShape=1+.11*Math.sin(a*3+.55)+.065*Math.sin(a*5-1.15)+.045*Math.cos(a*7+.8);const peninsula=.18*Math.exp(-Math.pow(this.angularDistance(a,-.42)/.34,2));const shoulder=.08*Math.exp(-Math.pow(this.angularDistance(a,1.05)/.5,2));const bay=.16*Math.exp(-Math.pow(this.angularDistance(a,2.38)/.3,2));return r/(this.radius*Math.max(.72,baseShape+peninsula+shoulder-bay));}
 gaussian(x,z,cx,cz,sx,sz,height){const dx=(x-cx)/sx,dz=(z-cz)/sz;return height*Math.exp(-(dx*dx+dz*dz));}
 rotatedGaussian(x,z,cx,cz,angle,longRadius,shortRadius,height){const dx=x-cx,dz=z-cz,c=Math.cos(angle),s=Math.sin(angle),u=(dx*c+dz*s)/longRadius,v=(-dx*s+dz*c)/shortRadius;return height*Math.exp(-(u*u+v*v));}
 cliffPoint(t){const u=(t-.5)*64,base=-.72,c=Math.cos(base),s=Math.sin(base),nx=-s,nz=c;const bend=Math.sin(t*Math.PI*1.55)*5.4+Math.sin(t*Math.PI*3.9+1.0)*2.2+Math.sin(t*Math.PI*7.1+.35)*.7;return{x:-48+u*c+nx*bend,z:-12+u*s+nz*bend};}
 cliffFrame(t){const p=this.cliffPoint(t),a=this.cliffPoint(Math.max(0,t-.01)),b=this.cliffPoint(Math.min(1,t+.01));let tx=b.x-a.x,tz=b.z-a.z,l=Math.hypot(tx,tz)||1;tx/=l;tz/=l;return{...p,tx,tz,nx:-tz,nz:tx};}
 cliffField(x,z){let best=null;for(let i=0;i<=24;i++){const t=i/24,p=this.cliffPoint(t),d2=(x-p.x)**2+(z-p.z)**2;if(!best||d2<best.d2)best={t,d2};}const f=this.cliffFrame(best.t),dx=x-f.x,dz=z-f.z,signed=dx*f.nx+dz*f.nz,dist=Math.sqrt(best.d2);const alongFade=Math.sin(Math.PI*Math.min(1,Math.max(0,best.t)))**.65;const widthFade=Math.exp(-Math.pow(dist/28,2));const amp=(2.6+.7*Math.sin(best.t*Math.PI*2.3+1.1))*alongFade*widthFade;return{height:amp*Math.tanh(signed/3.4),frame:f,signed,dist,t:best.t};}
 rawHeightAt(x,z){const d=this.islandMetric(x,z);if(d>=1)return this.seabedLevel;const broad=Math.sin(x*.024+z*.008)*.75+Math.cos(z*.027-x*.006)*.65+Math.sin((x-z)*.043)*.28;let h=1.45+broad;h+=this.gaussian(x,z,-42,30,34,29,10.8);h+=this.rotatedGaussian(x,z,35,-20,-.58,55,15,5.2);h+=this.gaussian(x,z,48,38,31,24,4.6);h+=this.gaussian(x,z,-8,-42,35,28,-3.7);h+=this.gaussian(x,z,62,-58,38,24,-1.3);h+=this.cliffField(x,z).height;const spawnBlend=Math.exp(-(x*x+z*z)/(22*22));h=h*(1-spawnBlend*.28)+(2.8+broad*.18)*(spawnBlend*.28);const coast=Math.max(0,1-d),coastEase=Math.min(1,coast/.16),eased=coastEase*coastEase*(3-2*coastEase),shore=-.35+h*.12;return Math.max(-.6,shore*(1-eased)+h*eased);}
 heightAt(x,z){return this.rawHeightAt(x,z);}
 slopeAt(x,z){const e=1,h=this.heightAt(x,z);return Math.max(Math.abs(this.heightAt(x+e,z)-h),Math.abs(this.heightAt(x-e,z)-h),Math.abs(this.heightAt(x,z+e)-h),Math.abs(this.heightAt(x,z-e)-h))/e;}
 createLandMaterial(geometry){const T=this.T,p=geometry.attributes.position,colors=new Float32Array(p.count*3),grass=new T.Color(0x7fb64e),grassDark=new T.Color(0x6da246),grassLight=new T.Color(0x8cc65b),soil=new T.Color(0x7a6b4b),stone=new T.Color(0x7d8681),stoneDark=new T.Color(0x69736f),seabed=new T.Color(0x64745e);for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i),z=p.getZ(i),d=this.islandMetric(x,z),s=this.slopeAt(x,z);let c;if(d>=1)c=seabed;else if(d>.955)c=soil;else if(s>.78)c=stoneDark;else if(s>.43)c=stone;else if(y>7.5)c=grassLight;else if(y<1.1)c=grassDark;else c=grass;colors[i*3]=c.r;colors[i*3+1]=c.g;colors[i*3+2]=c.b;}geometry.setAttribute('color',new T.BufferAttribute(colors,3));return new T.MeshStandardMaterial({vertexColors:true,roughness:.95,metalness:0,flatShading:true});}
 create(){const T=this.T,root=new T.Group();root.name='IslandWorld';const size=this.radius*2.42,geo=new T.PlaneGeometry(size,size,176,176);geo.rotateX(-Math.PI/2);const p=geo.attributes.position;for(let i=0;i<p.count;i++)p.setY(i,this.heightAt(p.getX(i),p.getZ(i)));geo.computeVertexNormals();const land=new T.Mesh(geo,this.createLandMaterial(geo));land.name='AsymmetricIslandLand';land.receiveShadow=true;root.add(land);const oceanGeo=new T.PlaneGeometry(700,700,1,1);oceanGeo.rotateX(-Math.PI/2);const ocean=new T.Mesh(oceanGeo,new T.MeshPhongMaterial({color:0x43b7d5,shininess:55,specular:0x9fe7ef,depthWrite:true,polygonOffset:true,polygonOffsetFactor:-1,polygonOffsetUnits:-1}));ocean.name='OceanSurface';ocean.position.y=this.seaLevel;root.add(ocean);return root;}
}
