const release = window.__THE_VILLAGER_RELEASE__;
if (!release?.releaseId || !release?.assets || !release?.playerAtlas) throw new Error('Phaser runtime requires the active release manifest.');
const Phaser = window.Phaser;if (!Phaser) throw new Error('Phaser engine failed to load.');
function moduleUrl(path){const url=new URL(path,import.meta.url);url.searchParams.set('r',release.releaseId);return url.href;}
function assetUrl(key){const path=release.assets[key];if(!path)return null;const url=new URL(`../${path}`,import.meta.url);url.searchParams.set('r',release.releaseId);return url.href;}
const [configModule,inventoryModule,inputModule,resourcesModule,craftingModule,villageModule,environmentArtModule]=await Promise.all([import(moduleUrl('./config.js')),import(moduleUrl('./inventory.js')),import(moduleUrl('./input.js')),import(moduleUrl('./resources.js')),import(moduleUrl('./crafting.js')),import(moduleUrl('./village.js')),import(moduleUrl('./environment-art.js'))]);
const {GAME_CONFIG}=configModule;const {Inventory,renderInventory}=inventoryModule;const {VirtualJoystick}=inputModule;const {createStarterResources}=resourcesModule;const {CraftingSystem,renderCrafting}=craftingModule;const {VILLAGE_CONFIG,createVillage}=villageModule;const {createWorldArt}=environmentArtModule;
const root=document.getElementById('phaser-root');const joystick=new VirtualJoystick(document.getElementById('joystick'),document.getElementById('joystick-knob'));
const targetPanel=document.getElementById('target-panel'),targetName=document.getElementById('target-name'),toolName=document.getElementById('tool-name'),harvestProgress=document.getElementById('harvest-progress'),inventoryPanel=document.getElementById('inventory-panel'),craftingPanel=document.getElementById('crafting-panel'),inventoryGrid=document.getElementById('inventory-grid'),craftingList=document.getElementById('crafting-list'),equippedTools=document.getElementById('equipped-tools'),inventoryButton=document.getElementById('inventory-button'),craftingButton=document.getElementById('crafting-button'),inventoryClose=document.getElementById('inventory-close'),craftingClose=document.getElementById('crafting-close');
let crafting=null;const inventory=new Inventory(refreshPanels);crafting=new CraftingSystem(inventory,refreshPanels);refreshPanels();
inventoryButton.addEventListener('click',()=>openPanel(inventoryPanel));craftingButton.addEventListener('click',()=>openPanel(craftingPanel));inventoryClose.addEventListener('click',()=>inventoryPanel.classList.add('hidden'));craftingClose.addEventListener('click',()=>craftingPanel.classList.add('hidden'));
const keyboard=new Set();window.addEventListener('keydown',e=>keyboard.add(e.key.toLowerCase()));window.addEventListener('keyup',e=>keyboard.delete(e.key.toLowerCase()));
function openPanel(panel){inventoryPanel.classList.add('hidden');craftingPanel.classList.add('hidden');panel.classList.remove('hidden');window.__THE_VILLAGER_SCENE__?.clearHarvestTarget();}
function anyPanelOpen(){return !inventoryPanel.classList.contains('hidden')||!craftingPanel.classList.contains('hidden');}
function refreshPanels(){renderInventory(inventoryGrid,inventory);if(!crafting)return;renderCrafting(craftingList,crafting,inventory);renderEquippedTools();}
function renderEquippedTools(){equippedTools.innerHTML='';[['axe','Trees'],['pickaxe','Stone'],['sickle','Grass']].forEach(([cls,label])=>{const tool=crafting.getEquipped(cls),chip=document.createElement('div');chip.className='equipped-chip';chip.textContent=tool?`${label}: ${tool.name}`:`${label}: Hands`;equippedTools.appendChild(chip);});}
class VillagerScene extends Phaser.Scene{constructor(){super('villager-world');this.resources=createStarterResources();this.resourceSprites=new Map();this.currentTarget=null;this.harvestElapsed=0;this.movementMagnitude=0;this.facingX=0;this.facingY=1;this.village=null;this.worldArt=null;}
preload(){for(const key of ['tree','rock','grass','villageCottage','villageHall','villageWorkshop','villageWell']){const src=assetUrl(key);if(src)this.load.image(key==='villageCottage'?'village-cottage':key==='villageHall'?'village-hall':key==='villageWorkshop'?'village-workshop':key==='villageWell'?'village-well':key,src);}this.load.spritesheet('player',assetUrl('playerSheet'),{frameWidth:release.playerAtlas.frameWidth,frameHeight:release.playerAtlas.frameHeight});this.load.on('loaderror',file=>console.error('Phaser asset load failed:',file?.key,file?.src));}
create(){window.__THE_VILLAGER_SCENE__=this;this.cameras.main.setBackgroundColor('#315f2f');this.cameras.main.setBounds(0,0,GAME_CONFIG.world.width,GAME_CONFIG.world.height);this.physics.world.setBounds(0,0,GAME_CONFIG.world.width,GAME_CONFIG.world.height);this.worldArt=createWorldArt(this,GAME_CONFIG);this.village=createVillage(this);this.createResources();this.createPlayer();this.createPlayerAnimation();this.physics.add.collider(this.player,this.village.blockers);this.cameras.main.startFollow(this.player,true,GAME_CONFIG.camera.followLerp,GAME_CONFIG.camera.followLerp);this.cameras.main.setZoom(GAME_CONFIG.camera.zoom);this.cameras.main.setRoundPixels(true);this.scale.on('resize',()=>{this.cameras.main.setSize(window.innerWidth,window.innerHeight);this.cameras.main.setZoom(GAME_CONFIG.camera.zoom);});}
createResources(){for(const node of this.resources){const sprite=this.add.image(node.x,node.y,node.type);sprite.setOrigin(.5,.88);sprite.setDepth(node.y);if(node.type==='tree')sprite.setDisplaySize(160,218);else if(node.type==='rock')sprite.setDisplaySize(132,92);else sprite.setDisplaySize(64,76);this.resourceSprites.set(node,sprite);}}
createPlayer(){const atlas=release.playerAtlas;this.player=this.physics.add.sprite(VILLAGE_CONFIG.spawn.x,VILLAGE_CONFIG.spawn.y,'player',0);this.player.setDisplaySize(atlas.drawWidth,atlas.drawHeight);this.player.setOrigin(.5,.82);this.player.setCollideWorldBounds(true);this.player.setDepth(VILLAGE_CONFIG.spawn.y+1);this.player.body.setSize(Math.max(18,Math.round(atlas.drawWidth*.28)),Math.max(20,Math.round(atlas.drawHeight*.25)),true);}
createPlayerAnimation(){const n=release.playerAtlas.columns;if(n<2)return;this.anims.create({key:'player-walk',frames:this.anims.generateFrameNumbers('player',{start:0,end:n-1}),frameRate:release.playerAtlas.walkFps||8,repeat:-1});}
update(_t,deltaMs){const dt=Math.min(deltaMs/1000,.05);if(anyPanelOpen()){this.player.setVelocity(0,0);this.stopWalking();this.clearHarvestTarget();}else{this.updatePlayer(dt);this.updateHarvest(dt);}this.updateResourceRespawns(dt);this.player.setDepth(this.player.y+1);}
updatePlayer(){const kx=(keyboard.has('arrowright')||keyboard.has('d')?1:0)-(keyboard.has('arrowleft')||keyboard.has('a')?1:0),ky=(keyboard.has('arrowdown')||keyboard.has('s')?1:0)-(keyboard.has('arrowup')||keyboard.has('w')?1:0),stick=joystick.getVector();let x=Math.abs(stick.x)>.08?stick.x:kx,y=Math.abs(stick.y)>.08?stick.y:ky,mag=Math.hypot(x,y);this.movementMagnitude=mag;if(mag>.001){x/=Math.max(1,mag);y/=Math.max(1,mag);this.facingX=x;this.facingY=y;this.player.setVelocity(x*GAME_CONFIG.player.speed,y*GAME_CONFIG.player.speed);if(!this.player.anims.isPlaying)this.player.play('player-walk');this.player.setFlipX(x<-.12);}else{this.player.setVelocity(0,0);this.stopWalking();}}
stopWalking(){if(this.player?.anims?.isPlaying)this.player.stop();}
updateHarvest(dt){let nearest=null,dist=Infinity;for(const n of this.resources){if(!n.active)continue;const d=Phaser.Math.Distance.Between(this.player.x,this.player.y,n.x,n.y);if(d<dist){nearest=n;dist=d;}}if(!nearest||dist>GAME_CONFIG.harvest.range){this.clearHarvestTarget();return;}const tool=crafting.getEquipped(nearest.toolClass);if(!tool){this.showTarget(nearest,'No tool equipped');this.harvestElapsed=0;return;}if(this.currentTarget!==nearest){this.currentTarget=nearest;this.harvestElapsed=0;}this.harvestElapsed+=dt;this.showTarget(nearest,tool.name);harvestProgress.style.width=`${Math.min(100,(this.harvestElapsed/GAME_CONFIG.harvest.duration)*100)}%`;if(this.harvestElapsed>=GAME_CONFIG.harvest.duration)this.completeHarvest(nearest);}
showTarget(node,tool){targetPanel.classList.remove('hidden');targetName.textContent=node.label;toolName.textContent=tool;}
clearHarvestTarget(){this.currentTarget=null;this.harvestElapsed=0;targetPanel.classList.add('hidden');harvestProgress.style.width='0%';}
completeHarvest(node){inventory.add(node.itemId,node.yield);node.active=false;node.respawnRemaining=GAME_CONFIG.harvest.respawnSeconds;this.resourceSprites.get(node)?.setVisible(false);this.clearHarvestTarget();}
updateResourceRespawns(dt){for(const n of this.resources){if(n.active)continue;n.respawnRemaining-=dt;if(n.respawnRemaining<=0){n.active=true;n.respawnRemaining=0;this.resourceSprites.get(n)?.setVisible(true);}}}}
new Phaser.Game({type:Phaser.AUTO,parent:root,width:window.innerWidth,height:window.innerHeight,backgroundColor:'#315f2f',pixelArt:true,roundPixels:true,physics:{default:'arcade',arcade:{debug:false}},scene:[VillagerScene],scale:{mode:Phaser.Scale.RESIZE,autoCenter:Phaser.Scale.CENTER_BOTH}});
